### ISSUE TITLE
Add support for incremental build

### ISSUE THREAD

**Issue by Dolfik1** [fabulousfx/FSharp.Android.Resource#1]
MSBuild has [incremental build](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-incrementally?view=vs-2022) support. 

It would be good to have incremental build support by this msbuild task. This will make it possible to get rid of the need to reload the project.

It should look something like this:

```targets
<Target 
  Name="CompileResourceDesignerForFSharp" 
  Inputs="$(MSBuildProjectName).fsproj" 
  Outputs="$(FSharpAndroidResource_AssemblyPath)"
  DependsOnTargets="ResolveProjectReferences;ResolveAssemblyReferences">
<!-- csc task -->
</Target>
```

**Comment by TimLariviere** [comment]
Incremental build has been added to version 0.0.2-beta
