### ISSUE TITLE
Running into UpdateIdValues not defined

### ISSUE THREAD

**Issue by tylerhartwig** [fabulousfx/FSharp.Android.Resource#3]
Hi all,

Using version 1.0.1 on macOS (and Rider) it seems that the F# Resources are not generated. The project is a simple Android project targeting 6.0. dotnet sdk 6.0.201. (note the command line build also fails with the same error)

The exact error is `MainActivity.fs(25, 18): [FS0039] The type 'Resource' does not define the field, constructor or member 'UpdateIdValues'.`

How best should I debug this?

**Comment by TimLariviere** [comment]
Could you try to build a 2nd time when you see this error?

On macOS, there is a limitation on the 1st build where the Resource dll is generated but not loaded by MSBuild.
The 2nd build should pick up the generated dll and everything should be fine.

If it's still crashing, you can try to build in diagnostic mode and share the log here.
```
dotnet build -v diag YourProject.fsproj > build.log
```

**Comment by tylerhartwig** [comment]
Thanks Tim!

Just found the issue, was a silly namespacing issue in the MainActivity file. Fixed that import and all is working now 😅
